import type { Metadata } from 'next';
import { Inter, Forum, DM_Sans } from 'next/font/google';
import './globals.css';
import { getServerSession } from 'next-auth/next';
import 'svgmap/dist/svgMap.min.css';
import NextAuthProvider from '@/utils/SessionProvider';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Providers from '@/Providers';
import SessionTimeoutWrapper from '@/components/SessionTimeoutWrapper';
import { ThemeProvider } from '@/context/ThemeContext';
import WishlistLoader from '@/components/WishlistLoader';
import ClientLayoutWrapper from '@/components/ClientLayoutWrapper'; // Import the new wrapper

const inter = Inter({ subsets: ['latin'] });
const forum = Forum({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-forum',
});
const dm_sans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-dm-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${forum.variable} ${dm_sans.variable}`}
      >
        <NextAuthProvider session={session}>
          <ThemeProvider>
            <Providers>
              <SessionTimeoutWrapper />
              <Header />
              <ClientLayoutWrapper>
                <main className="pt-[80px] relative z-10 mb-20 min-h-screen">
                  <WishlistLoader>{children}</WishlistLoader>
                </main>
              </ClientLayoutWrapper>
              <Footer />
            </Providers>
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
